name: Fortify Scan

on:
  push:
    branches: [main]

jobs:
  fortify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fortify Scan
        uses: fortify/gha-setup-fod-uploader@v1
        with:
          fod_api_url: ${{ secrets.FOD_API_URL }}
          fod_client_id: ${{ secrets.FOD_CLIENT_ID }}
          fod_client_secret: ${{ secrets.FOD_CLIENT_SECRET }}
