name: SLSA Generic generator

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}
    steps:
      - uses: actions/checkout@v4
      - name: Build artifacts
        run: |
          echo "Build your project and produce release artifacts"
      - name: Generate hashes
        id: hash
        uses: slsa-framework/slsa-github-generator/.github/actions/generate-base64-subjects@v2.0.0
  provenance:
    needs: [build]
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: ${{ needs.build.outputs.digests }}
      upload-assets: true
